---
swagger: "2.0"
info:
  description: "This is a API document for Stylens Service"
  version: "0.0.2"
  title: "style-api"
  contact:
    email: "master@bluehack.net"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api-prod.stylelens.io"
basePath: "/"
tags:
- name: "feed"
  description: "feed"
- name: "image"
  description: "image"
- name: "playground"
  description: "playground"
schemes:
- "http"
paths:
  /feeds:
    get:
      tags:
      - "feed"
      summary: ""
      description: "Returns Main Feeds"
      operationId: "get_feeds"
      produces:
      - "application/json"
      parameters:
      - name: "offset"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      - name: "limit"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetFeedResponse"
        400:
          description: "Invalid input"
        404:
          description: "Feeds not found"
      x-swagger-router-controller: "swagger_server.controllers.feed_controller"
  /images:
    get:
      tags:
      - "image"
      summary: "Get Images by imageId"
      description: "Returns similar Images with imageId"
      operationId: "get_images"
      produces:
      - "application/json"
      parameters:
      - name: "imageId"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "offset"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      - name: "limit"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetImagesResponse"
        400:
          description: "Invalid input supplied"
        404:
          description: "imageId or objectId not found"
      x-swagger-router-controller: "swagger_server.controllers.image_controller"
  /images/{imageId}:
    get:
      tags:
      - "image"
      summary: "Find Images by ID"
      description: "Returns a single Image"
      operationId: "get_image_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "imageId"
        in: "path"
        description: "ID of Image to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetImageResponse"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Image not found"
      x-swagger-router-controller: "swagger_server.controllers.image_controller"
  /images/objects/{objectId}:
    get:
      tags:
      - "image"
      summary: "Query to search images by object id"
      description: ""
      operationId: "get_images_by_object_id"
      produces:
      - "application/json"
      parameters:
      - name: "objectId"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "offset"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      - name: "limit"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetImagesResponse"
        400:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.image_controller"
  /images/userImages:
    post:
      tags:
      - "image"
      summary: "Query to search images"
      description: ""
      operationId: "get_images_by_user_image_file"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "User's Image file to upload (only support jpg format yet)"
        required: false
        type: "file"
      - name: "offset"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      - name: "limit"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetImagesResponse"
        400:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.image_controller"
  /images/userImages/{userImageId}/objects/{objectIndex}:
    get:
      tags:
      - "image"
      summary: "Get Images by userImageId and objectIndex"
      description: "Returns Images belongs to a userImageId and objectIndex"
      operationId: "get_images_by_user_image_id_and_object_index"
      produces:
      - "application/json"
      parameters:
      - name: "userImageId"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "objectIndex"
        in: "path"
        description: ""
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetImagesResponse"
        400:
          description: "Invalid input supplied"
        404:
          description: "userImageId or objectIndex not found"
      x-swagger-router-controller: "swagger_server.controllers.image_controller"
  /images/hosts/{hostCode}/images/{productNo}:
    get:
      tags:
      - "image"
      summary: "Get Image by hostCode and productNo"
      description: "Returns Image belongs to a Host and productNo"
      operationId: "get_image_by_hostcode_and_product_no"
      produces:
      - "application/json"
      parameters:
      - name: "hostCode"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "productNo"
        in: "path"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetImageResponse"
        400:
          description: "Invalid input supplied"
        404:
          description: "Host or productNo not found"
      x-swagger-router-controller: "swagger_server.controllers.image_controller"
  /objects:
    post:
      tags:
      - "object"
      summary: "Query to search objects and images"
      description: ""
      operationId: "get_objects_by_user_image_file"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "User's Image file to upload (only support jpg format yet)"
        required: true
        type: "file"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetObjectsResponse"
        400:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.object_controller"
  /objects/images/{imageId}:
    get:
      tags:
      - "object"
      summary: "Query to search multiple objects"
      description: ""
      operationId: "get_objects_by_image_id"
      produces:
      - "application/json"
      parameters:
      - name: "imageId"
        in: "path"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetObjectsByImageIdResponse"
        400:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.object_controller"
  /playgrounds/objects:
    post:
      tags:
      - "playground"
      summary: ""
      description: ""
      operationId: "get_playground_objects_by_user_image_file"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "User's Image file to upload (only support jpg format yet)"
        required: true
        type: "file"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetObjectsResponse"
        400:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.playground_controller"
  /playgrounds/images:
    get:
      tags:
      - "playground"
      summary: "Query to search multiple objects"
      description: ""
      operationId: "get_images_by_keyword"
      produces:
      - "application/json"
      parameters:
      - name: "keyword"
        in: "query"
        description: ""
        required: false
        type: "string"
      - name: "categoryName"
        in: "query"
        description: ""
        required: false
        type: "string"
      - name: "offset"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      - name: "limit"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetImagesByKeywordResponse"
        400:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.playground_controller"
  /playgrounds/images/datasets/{source}/categories:
    get:
      tags:
      - "playground"
      summary: "Query to search multiple objects"
      description: ""
      operationId: "get_images_dataset_by_category"
      produces:
      - "application/json"
      parameters:
      - name: "source"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "category"
        in: "query"
        description: ""
        required: false
        type: "string"
      - name: "offset"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      - name: "limit"
        in: "query"
        description: ""
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetImagesByCategoryResponse"
        400:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.playground_controller"
  /playgrounds/images/datasets/{source}/categories/counts:
    get:
      tags:
      - "playground"
      summary: "Query to search category counts"
      description: ""
      operationId: "get_images_dataset_categories_counts_by_category"
      produces:
      - "application/json"
      parameters:
      - name: "source"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "category"
        in: "query"
        description: ""
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetImagesCategoriesCountsByCategoryResponse"
        400:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.playground_controller"
  /playgrounds/images/datasets/{source}:
    post:
      tags:
      - "playground"
      summary: "Update image"
      description: ""
      operationId: "update_images_dataset_by_ids"
      produces:
      - "application/json"
      parameters:
      - name: "source"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "ids"
        in: "query"
        description: ""
        required: true
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      - name: "valid"
        in: "query"
        description: ""
        required: true
        type: "boolean"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UpdateImageDatasetResponse"
        400:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.playground_controller"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Image:
    type: "object"
    properties:
      id:
        type: "string"
      product_name:
        type: "string"
      product_id:
        type: "string"
      host_code:
        type: "string"
      host_url:
        type: "string"
      host_name:
        type: "string"
      class_code:
        type: "string"
        example: ""
      price:
        type: "integer"
        format: "int32"
      currency_unit:
        type: "string"
      product_url:
        type: "string"
      product_no:
        type: "string"
      nation:
        type: "string"
      main_image_mobile_full:
        type: "string"
        description: "Mobile full size of image url"
      main_image_mobile_thumb:
        type: "string"
        description: "Mobile thumbnail size of image url"
      version:
        type: "string"
      images:
        type: "array"
        items:
          $ref: "#/definitions/SimImage"
    example:
      host_url: "host_url"
      main_image_mobile_thumb: "main_image_mobile_thumb"
      images:
      - host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_name: "product_name"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        host_code: "host_code"
        price: 6
        product_id: "product_id"
        id: "id"
        host_name: "host_name"
        class_code: ""
      - host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_name: "product_name"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        host_code: "host_code"
        price: 6
        product_id: "product_id"
        id: "id"
        host_name: "host_name"
        class_code: ""
      product_url: "product_url"
      nation: "nation"
      currency_unit: "currency_unit"
      product_name: "product_name"
      product_no: "product_no"
      main_image_mobile_full: "main_image_mobile_full"
      version: "version"
      host_code: "host_code"
      price: 0
      product_id: "product_id"
      id: "id"
      host_name: "host_name"
      class_code: ""
  SimImage:
    type: "object"
    properties:
      id:
        type: "string"
      product_name:
        type: "string"
      product_id:
        type: "string"
      host_code:
        type: "string"
      host_url:
        type: "string"
      host_name:
        type: "string"
      class_code:
        type: "string"
        example: ""
      price:
        type: "integer"
        format: "int32"
      currency_unit:
        type: "string"
      product_url:
        type: "string"
      product_no:
        type: "string"
      nation:
        type: "string"
      main_image_mobile_full:
        type: "string"
        description: "Mobile full size of image url"
      main_image_mobile_thumb:
        type: "string"
        description: "Mobile thumbnail size of image url"
      version:
        type: "string"
    example:
      host_url: "host_url"
      main_image_mobile_thumb: "main_image_mobile_thumb"
      product_url: "product_url"
      nation: "nation"
      currency_unit: "currency_unit"
      product_name: "product_name"
      product_no: "product_no"
      main_image_mobile_full: "main_image_mobile_full"
      version: "version"
      host_code: "host_code"
      price: 6
      product_id: "product_id"
      id: "id"
      host_name: "host_name"
      class_code: ""
  SimpleImage:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      product_id:
        type: "string"
      host_code:
        type: "string"
      host_url:
        type: "string"
      host_name:
        type: "string"
      class_code:
        type: "string"
        example: ""
      cate:
        type: "array"
        items:
          type: "string"
      tags:
        type: "string"
      price:
        type: "integer"
        format: "int32"
      currency_unit:
        type: "string"
      product_url:
        type: "string"
      product_no:
        type: "string"
      nation:
        type: "string"
      main_image_mobile_full:
        type: "string"
        description: "Mobile full size of image url"
      main_image_mobile_thumb:
        type: "string"
        description: "Mobile thumbnail size of image url"
      version:
        type: "string"
    example:
      cate:
      - "cate"
      - "cate"
      host_url: "host_url"
      main_image_mobile_thumb: "main_image_mobile_thumb"
      product_url: "product_url"
      nation: "nation"
      currency_unit: "currency_unit"
      product_no: "product_no"
      main_image_mobile_full: "main_image_mobile_full"
      version: "version"
      tags: "tags"
      host_code: "host_code"
      price: 0
      product_id: "product_id"
      name: "name"
      id: "id"
      host_name: "host_name"
      class_code: ""
  BoxDataset:
    type: "object"
    properties:
      x1:
        type: "number"
        format: "float"
      y1:
        type: "number"
        format: "float"
      x2:
        type: "number"
        format: "float"
      y2:
        type: "number"
        format: "float"
    example:
      y1: 6.0274563
      x1: 0.8008282
      y2: 5.962134
      x2: 1.4658129
  ImageDataset:
    type: "object"
    properties:
      id:
        type: "string"
      bbox:
        $ref: "#/definitions/BoxDataset"
      category_class:
        type: "string"
      category_name:
        type: "string"
      height:
        type: "integer"
        format: "int32"
      width:
        type: "integer"
        format: "int32"
      source:
        type: "string"
      url:
        type: "string"
      url_with_box:
        type: "string"
    example:
      category_class: "category_class"
      category_name: "category_name"
      bbox:
        y1: 6.0274563
        x1: 0.8008282
        y2: 5.962134
        x2: 1.4658129
      width: 2
      url_with_box: "url_with_box"
      id: "id"
      source: "source"
      url: "url"
      height: 5
  ImagesArray:
    type: "array"
    items:
      $ref: "#/definitions/Image"
  Box:
    type: "object"
    properties:
      left:
        type: "number"
        format: "float"
      right:
        type: "number"
        format: "float"
      top:
        type: "number"
        format: "float"
      bottom:
        type: "number"
        format: "float"
    example:
      top: 1.4658129
      left: 0.8008282
      bottom: 5.962134
      right: 6.0274563
  BoxesArray:
    type: "array"
    items:
      $ref: "#/definitions/BoxObject"
  BoxObject:
    type: "object"
    properties:
      id:
        type: "string"
      box:
        $ref: "#/definitions/Box"
      image_id:
        type: "string"
      version_id:
        type: "string"
      class_code:
        type: "string"
      color_code:
        type: "string"
      color_score:
        type: "number"
        format: "float"
      score:
        type: "number"
        format: "float"
    example:
      score: 2.302136
      color_score: 5.637377
      box:
        top: 1.4658129
        left: 0.8008282
        bottom: 5.962134
        right: 6.0274563
      id: "id"
      version_id: "version_id"
      image_id: "image_id"
      class_code: "class_code"
      color_code: "color_code"
  GetImageResponse:
    type: "object"
    properties:
      message:
        type: "string"
      data:
        $ref: "#/definitions/Image"
    example:
      data:
        host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        images:
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_name: "product_name"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        host_code: "host_code"
        price: 0
        product_id: "product_id"
        id: "id"
        host_name: "host_name"
        class_code: ""
      message: "message"
  GetFeedResponse:
    type: "object"
    properties:
      message:
        type: "string"
      data:
        type: "array"
        items:
          $ref: "#/definitions/Image"
    example:
      data:
      - host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        images:
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_name: "product_name"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        host_code: "host_code"
        price: 0
        product_id: "product_id"
        id: "id"
        host_name: "host_name"
        class_code: ""
      - host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        images:
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_name: "product_name"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        host_code: "host_code"
        price: 0
        product_id: "product_id"
        id: "id"
        host_name: "host_name"
        class_code: ""
      message: "message"
  GetObjectsResponse:
    type: "object"
    properties:
      message:
        type: "string"
      data:
        $ref: "#/definitions/GetObjectsResponse_data"
    example:
      data:
        boxes:
        - score: 2.302136
          color_score: 5.637377
          box:
            top: 1.4658129
            left: 0.8008282
            bottom: 5.962134
            right: 6.0274563
          id: "id"
          version_id: "version_id"
          image_id: "image_id"
          class_code: "class_code"
          color_code: "color_code"
        - score: 2.302136
          color_score: 5.637377
          box:
            top: 1.4658129
            left: 0.8008282
            bottom: 5.962134
            right: 6.0274563
          id: "id"
          version_id: "version_id"
          image_id: "image_id"
          class_code: "class_code"
          color_code: "color_code"
        images:
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        image_id: "image_id"
      message: "message"
  GetObjectsByImageIdResponse:
    type: "object"
    properties:
      message:
        type: "string"
      data:
        $ref: "#/definitions/GetObjectsResponse_data"
    example:
      data:
        boxes:
        - score: 2.302136
          color_score: 5.637377
          box:
            top: 1.4658129
            left: 0.8008282
            bottom: 5.962134
            right: 6.0274563
          id: "id"
          version_id: "version_id"
          image_id: "image_id"
          class_code: "class_code"
          color_code: "color_code"
        - score: 2.302136
          color_score: 5.637377
          box:
            top: 1.4658129
            left: 0.8008282
            bottom: 5.962134
            right: 6.0274563
          id: "id"
          version_id: "version_id"
          image_id: "image_id"
          class_code: "class_code"
          color_code: "color_code"
        images:
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        image_id: "image_id"
      message: "message"
  SearchImageResponse:
    type: "object"
    properties:
      message:
        type: "string"
      data:
        type: "array"
        items:
          $ref: "#/definitions/Image"
  GetImagesResponse:
    type: "object"
    properties:
      message:
        type: "string"
      data:
        type: "array"
        items:
          $ref: "#/definitions/Image"
    example:
      data:
      - host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        images:
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_name: "product_name"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        host_code: "host_code"
        price: 0
        product_id: "product_id"
        id: "id"
        host_name: "host_name"
        class_code: ""
      - host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        images:
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        - host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_name: "product_name"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          host_code: "host_code"
          price: 6
          product_id: "product_id"
          id: "id"
          host_name: "host_name"
          class_code: ""
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_name: "product_name"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        host_code: "host_code"
        price: 0
        product_id: "product_id"
        id: "id"
        host_name: "host_name"
        class_code: ""
      message: "message"
  GetImagesByKeywordResponse:
    type: "object"
    properties:
      message:
        type: "string"
      data:
        $ref: "#/definitions/GetImagesByKeywordResponse_data"
    example:
      data:
        images:
        - cate:
          - "cate"
          - "cate"
          host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          tags: "tags"
          host_code: "host_code"
          price: 0
          product_id: "product_id"
          name: "name"
          id: "id"
          host_name: "host_name"
          class_code: ""
        - cate:
          - "cate"
          - "cate"
          host_url: "host_url"
          main_image_mobile_thumb: "main_image_mobile_thumb"
          product_url: "product_url"
          nation: "nation"
          currency_unit: "currency_unit"
          product_no: "product_no"
          main_image_mobile_full: "main_image_mobile_full"
          version: "version"
          tags: "tags"
          host_code: "host_code"
          price: 0
          product_id: "product_id"
          name: "name"
          id: "id"
          host_name: "host_name"
          class_code: ""
        total_count: "total_count"
      message: "message"
  GetImagesByCategoryResponse:
    type: "object"
    properties:
      message:
        type: "string"
      data:
        $ref: "#/definitions/GetImagesByCategoryResponse_data"
    example:
      data:
        images:
        - category_class: "category_class"
          category_name: "category_name"
          bbox:
            y1: 6.0274563
            x1: 0.8008282
            y2: 5.962134
            x2: 1.4658129
          width: 2
          url_with_box: "url_with_box"
          id: "id"
          source: "source"
          url: "url"
          height: 5
        - category_class: "category_class"
          category_name: "category_name"
          bbox:
            y1: 6.0274563
            x1: 0.8008282
            y2: 5.962134
            x2: 1.4658129
          width: 2
          url_with_box: "url_with_box"
          id: "id"
          source: "source"
          url: "url"
          height: 5
        total_count: "total_count"
      message: "message"
  GetImagesCategoriesCountsByCategoryResponse:
    type: "object"
    properties:
      message:
        type: "string"
      data:
        $ref: "#/definitions/GetImagesCategoriesCountsByCategoryResponse_data"
    example:
      data:
        total_count: "total_count"
        valid_count: "valid_count"
        invalid_count: "invalid_count"
      message: "message"
  UpdateImageDatasetResponse:
    type: "object"
    properties:
      message:
        type: "string"
    example:
      message: "message"
  GetObjectsResponse_data:
    properties:
      boxes:
        type: "array"
        items:
          $ref: "#/definitions/BoxObject"
      image_id:
        type: "string"
      images:
        type: "array"
        items:
          $ref: "#/definitions/SimImage"
    example:
      boxes:
      - score: 2.302136
        color_score: 5.637377
        box:
          top: 1.4658129
          left: 0.8008282
          bottom: 5.962134
          right: 6.0274563
        id: "id"
        version_id: "version_id"
        image_id: "image_id"
        class_code: "class_code"
        color_code: "color_code"
      - score: 2.302136
        color_score: 5.637377
        box:
          top: 1.4658129
          left: 0.8008282
          bottom: 5.962134
          right: 6.0274563
        id: "id"
        version_id: "version_id"
        image_id: "image_id"
        class_code: "class_code"
        color_code: "color_code"
      images:
      - host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_name: "product_name"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        host_code: "host_code"
        price: 6
        product_id: "product_id"
        id: "id"
        host_name: "host_name"
        class_code: ""
      - host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_name: "product_name"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        host_code: "host_code"
        price: 6
        product_id: "product_id"
        id: "id"
        host_name: "host_name"
        class_code: ""
      image_id: "image_id"
  GetImagesByKeywordResponse_data:
    properties:
      total_count:
        type: "string"
      images:
        type: "array"
        items:
          $ref: "#/definitions/SimpleImage"
    example:
      images:
      - cate:
        - "cate"
        - "cate"
        host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        tags: "tags"
        host_code: "host_code"
        price: 0
        product_id: "product_id"
        name: "name"
        id: "id"
        host_name: "host_name"
        class_code: ""
      - cate:
        - "cate"
        - "cate"
        host_url: "host_url"
        main_image_mobile_thumb: "main_image_mobile_thumb"
        product_url: "product_url"
        nation: "nation"
        currency_unit: "currency_unit"
        product_no: "product_no"
        main_image_mobile_full: "main_image_mobile_full"
        version: "version"
        tags: "tags"
        host_code: "host_code"
        price: 0
        product_id: "product_id"
        name: "name"
        id: "id"
        host_name: "host_name"
        class_code: ""
      total_count: "total_count"
  GetImagesByCategoryResponse_data:
    properties:
      total_count:
        type: "string"
      images:
        type: "array"
        items:
          $ref: "#/definitions/ImageDataset"
    example:
      images:
      - category_class: "category_class"
        category_name: "category_name"
        bbox:
          y1: 6.0274563
          x1: 0.8008282
          y2: 5.962134
          x2: 1.4658129
        width: 2
        url_with_box: "url_with_box"
        id: "id"
        source: "source"
        url: "url"
        height: 5
      - category_class: "category_class"
        category_name: "category_name"
        bbox:
          y1: 6.0274563
          x1: 0.8008282
          y2: 5.962134
          x2: 1.4658129
        width: 2
        url_with_box: "url_with_box"
        id: "id"
        source: "source"
        url: "url"
        height: 5
      total_count: "total_count"
  GetImagesCategoriesCountsByCategoryResponse_data:
    properties:
      total_count:
        type: "string"
      valid_count:
        type: "string"
      invalid_count:
        type: "string"
    example:
      total_count: "total_count"
      valid_count: "valid_count"
      invalid_count: "invalid_count"
externalDocs:
  description: "Find out more about BlueLens"
  url: "http://bluelens.io"
